global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']

  - job_name: 'organization-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8081']

  - job_name: 'department-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8082']

  - job_name: 'employee-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8083']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: config-user
      password: config-pass
    static_configs:
      - targets: ['172.17.0.1:8888']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: eureka-user
      password: eureka-pass
    static_configs:
      - targets: ['172.17.0.1:8761']
